#!/bin/bash

mount -t devtmpfs dev /dev
mount -t devpts devpts /dev/pts
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs run /run

export uname=$(uname -r)

insmod /usr/lib/modules/$uname/kernel/drivers/input/serio/libps2.ko
insmod /usr/lib/modules/$uname/kernel/drivers/input/serio/serio.ko
insmod /usr/lib/modules/$uname/kernel/drivers/input/vivaldi-fmap.ko
insmod /usr/lib/modules/$uname/kernel/drivers/input/keyboard/atkbd.ko

bash --login